### PR TITLE
fix example for API access

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by mathieudutour** [comment]
The readme corresponds to the new API that's going to ship with Sketch 49. So it's actually correct ;)

**Comment by DanielRuf** [comment]
So it is a breaking change and it has changed? Is there some reference for all changes?

**Comment by mathieudutour** [comment]
the old API (`context.api()`) will continue to work. We are providing a new API to start with some good foundations.

All the docs are here: https://github.com/BohemianCoding/SketchAPI/tree/develop/docs. They are not deployed yet since Sketch 49 is not released yet.

**Comment by mathieudutour** [comment]
If you want to have a look at the old API, here it is: https://github.com/BohemianCoding/SketchAPI/tree/release/48.2

**Comment by DanielRuf** [comment]
Ok, thanks for the info.

**Pull request closed without merging**
