### PR TITLE
Code Review: remove SketchAPI as a submodule (#17642)

### PR DESCRIPTION
**Pull request by mathieudutour**
Resolves BohemianCoding/Sketch#17642

### CODE REVIEW

**Comment by bohemian-coding-danger** [comment]
__To test the changes from the PR, replace `require('sketch')` by `require('__pr')('164')`__
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by christianklotz** [comment]
Is this PR still relevant?

**Comment by mathieudutour** [comment]
the issue is still relevant yes

**Comment by christianklotz** [comment]
Ok, super. What's missing before it can be merged apart from the branch conflicts?

**Comment by mathieudutour** [comment]
all the unticked checked boxes from the issue 😄

**Comment by christianklotz** [comment]
This has now been addressed separately, closing.

**Pull request closed without merging**
