### PR TITLE
Readme / API Changes that I think are missing and get in my way :)

### PR DESCRIPTION
**Pull request by mossyblog**
as you need to point the default writes to the appropriate .plist

### CODE REVIEW

**Comment by plrthink** [comment]
@mossyblog There's an issue with indent :)

**Comment by mossyblog** [comment]
Yeah I realised i had 4 spaces instead of 2, will fix

**Comment by mossyblog** [comment]
All good now

**Comment by plrthink** [comment]
but this line is still be indented more than 2 spaces.

https://github.com/mossyblog/SketchAPI/blob/8c0bb2e4cefe00395e6e6093cc97b7b17e253a27/Source/Layer.js#L89

**Comment by plrthink** [comment]
also the whole newPage function block

**Comment by mossyblog** [comment]
Yeah i pulled a totally rookie move just then.. deep apologies, tabs/spacing etc is now returning back to their factory defaults (I work in a team that get religious about this sort of thing and atom was configured differently)...

**Comment by plrthink** [comment]
It's ok. I think you could keep this pr open. The changes are great for the community.

**Comment by mossyblog** [comment]
Well.. i just realised there was a develop branch (didn't see it) which has most of this covered off... (still finding my feet here).

**Comment by plrthink** [comment]
But it seems like the command to overwrite the bundled SketchAPI is still missing? Or I just missing something. Pls correct me.

**Comment by mossyblog** [comment]
Yes, sorry that part is fine... i'll regroup and push a pull request via develop branch and merge changes...

**Pull request closed without merging**
