### PR TITLE
expose substrings in Text.fragments

### PR DESCRIPTION
**Pull request by mathieudutour**
See https://sketchplugins.com/d/1403-how-to-get-every-line-string-value-in-a-textlayer

### CODE REVIEW

**Comment by bohemian-coding-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  `Source/dom/layers/Text.js` changed, but not:
  - 📚 its docs

That's OK as long as you're refactoring.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e0edcee4b7b72c4c30af9638a3858f57fbb2c595
</p>

**Comment by KevinGutowski** [comment]
Not sure if this is the right location to ask but what is the `baselineOffset` property exactly?

**Comment by mathieudutour** [comment]
> the distance from the bottom of the line fragment rectangle in which the glyph resides to the glyph baseline

¯\_(ツ)_/¯

**Comment by KevinGutowski** [comment]
Ah, that's helpful thanks!

**Pull request merged**
