### PR TITLE
 Improve developer docs homepage visually

### PR DESCRIPTION
**Pull request by richardgazdik**
### Related issue
https://github.com/BohemianCoding/MarketingWebsite/issues/61

### CODE REVIEW

**Comment by robintindale** [comment]
Will this help with #598 ?

**Comment by robintindale** [comment]
Ah I tried the netlify deploy above, and seems like `File format` and `Sketch.app` still don't get highlighted. Otherwise, this looks fab :) One minor thing I noticed (which may just be a netlify issue), whenever I change page the font flashes on and off https://embed.cl.ly/c51689dd3c80

**Comment by KevinGutowski** [comment]
Just a small thing that I thought to mention. The code blocks seem to need a bit of `margin-bottom`

Screen Shot 2019-08-26 at 12 43 41 AM

**Comment by richardgazdik** [comment]
@Ana-ilundain-areso Could you pls review this PR when you have time:
https://deploy-preview-605--developer-sketch.netlify.com

### Description
This is a general design overhaul of the developer website and the following components are affected:
- updated home page
- unified search overlay 
- adaptive (mobile and tablet friendly) page layout which inherited the style and layout of the the Sketch Docs pages (https://sketch.com/docs)

### What to test
- Please test the whole page in more browsers and on mobile devices
- Please test the search component on desktop and mobile
- Please test the secondary navigation on desktop and mobile
- Please test the API Reference page's responsive layout in more browsers and on mobile (https://deploy-preview-605--developer-sketch.netlify.com/reference/api/)

**Comment by Ana-ilundain-areso** [comment]
✅ Page rendering correctly on Safari and Chrome desktop browsers
✅ Left margin section highlight correctly rendered when fast scrolling
✅ All links redirect correctly 
✅ No issues found on secondary navigation

🔴    Search results in desktop browser only shows result if you type at least 3 matching first letters. This occurs in production already. Should I file?
1. Go to plugins, search for `ru`

🔴 Search results or no results is not appearing on mobile (Safari) for any section except for `Api reference`. This is already happening too.

**Comment by richardgazdik** [comment]
@ana Updated the Lunr search engine plugin from v0.6 to v2.3.6 and results should be visible on mobile as well. The search component now show results after two typed characters (it was set to 3 beforehand)

**Comment by Ana-ilundain-areso** [comment]
@richardgazdik 
✅ Search on desktop browsers now shows results with only two letters.
✅ Search results are appearing correctly on mobile browser.

**Pull request merged**
